<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<style>
@page {
    size: A4;
    margin: 5%;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 10px;
@bottom-left {
font-family: Arial;
    font-size: 8px;
				content: "This page was generated by a computer at ${new Date()}";
}
    }


</style>



</head>

<body>

<h1>This is an example report for ${name}</h1>


</body>
</html>